name: Run deployment on release
'on':
  release:
    types: [released]

jobs:
  build_and_upload_artifact:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
      - run: |
          e="ver="
          ver=$(echo "${{ github.event.release.tag_name }}" | sed 's/^.//')
          echo "${e}${ver}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Gradle permission
        run: chmod +x ./gradlew
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Build llang
        run: ./gradlew package -Pversion=${{ env.ver }}
      - name: 'Upload llang artifact'
        uses: actions/upload-artifact@v3
        with:
          name: llang
          path: modules/exec/build/llang
          retention-days: 15
      - name: Zip lang
        run: zip -qq -r llang.zip llang
        working-directory: modules/exec/build
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: llang.zip
          asset_name: llang-${{ env.ver }}.zip
