name: Run deployment on release
'on':
  release:
    types: [released]

jobs:
  build_and_upload_artifact:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
      - run: |
          e="ver="
          ver=$(echo "${{ github.event.release.tag_name }}" | sed 's/^.//')
          echo "${e}${ver}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Gradle permission
        run: chmod +x ./gradlew
      - name: Build backend
        run: ./gradlew package -Pversion=${{ env.ver }}
      - name: 'Upload backend artifact'
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: modules/exec/build/llang
          retention-days: 15
      - name: Zip lang
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r llang.zip modules/exec/build/llang
      - name: Upload backend to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: llang.zip
          asset_name: backend-${{ env.ver }}.zip
