name: Run deployment on release
'on':
  release:
    types: [ released ]

jobs:
  build_and_upload_artifact:
    name: Build artifact
    runs-on: ubuntu-latest
    steps:
      - run: |
          e="ver="
          ver=$(echo "${{ github.event.release.tag_name }}" | sed 's/^.//')
          echo "${e}${ver}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Gradle permission
        run: chmod +x ./gradlew
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Build llang
        run: ./gradlew package -Pversion=${{ env.ver }}
      - name: 'Upload llang artifact'
        uses: actions/upload-artifact@v3
        with:
          name: llang
          path: modules/exec/build/llang
          retention-days: 15
      - name: Zip lang
        run: zip -qq -r llang.zip llang
        working-directory: modules/exec/build
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: modules/exec/build/llang.zip
          asset_name: llang-${{ env.ver }}.zip
      - name: Upload lib to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: modules/lang/build/libs/lang-${{ env.ver }}.jar
          asset_name: llang-lib-${{ env.ver }}.jar

  deploy_docs:
    name: Deploy docs to gh-pages
    runs-on: ubuntu-latest
    steps:
      - run: |
          e="ver="
          ver=$(echo "${{ github.event.release.tag_name }}" | sed 's/^.//')
          echo "${e}${ver}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        run: |
          cd modules/docs
          npm version ${{ env.ver }}
          npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: modules/docs/build # The folder the action should deploy.
